### ISSUE TITLE
Use process.env for token instead of a JSON file?

### ISSUE THREAD

**Issue by mauris** [teppeis/thank-you-stars#4]
Perhaps we can consider using environment variables to store the token, rather than using a JSON file?

**Comment by mauris** [comment]
@teppeis you're okay with me making the changes? will submit a PR for this issue.

**Comment by teppeis** [comment]
@mauris Yes, please PR!

**Comment by teppeis** [comment]
fixed in https://github.com/teppeis/thank-you-stars/pull/5
